### PR TITLE
Allow to save netrc file to disk

### PR DESCRIPTION
**Pull request by jtblin**

### CODE REVIEW

**Comment by jtblin** [comment]
Hi @camshaft any chance that you get this merged and publish to npm?

**Comment by camshaft** [comment]
You solution is overly complex. Is there a reason you didn't use [fs.writeFile](https://nodejs.org/api/fs.html#fs_fs_writefile_filename_data_options_callback)? I don't understand the need for creating the temp file either.

**Comment by jtblin** [comment]
Fair enough. We can remove the temp file and write directly via `fs.writeFile` if you're ok with merging that then?

**Comment by camshaft** [comment]
yes that would be great

**Comment by camshaft** [comment]
if you could also squash your commits that would be nice as well

**Comment by jtblin** [comment]
Done.

**Comment by camshaft** [comment]
Thanks!

**Comment by jtblin** [comment]
Thanks, can you publish this version to npm?

**Comment by camshaft** [comment]
done

**Pull request merged**
